[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "sh -c 'streamlit run streamlit_app.py --server.port=${PORT:-8080} --server.address=0.0.0.0'"
healthcheckPath = "/_stcore/health"
healthcheckTimeout = 600
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
